name: Patcher

on:
  workflow_dispatch:

jobs:
  build:
    name: Automatic rebase
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Fetch EvolutionX repo
      run: |
        git clone https://github.com/Evolution-X/frameworks_base -b snow base
        git clone https://github.com/Error-Project/patches patches
        
    - name: Apply Patch
      run: |
        cd base 
        git config user.name "Mihir Sahay"
        git config user.email "mihr.sahay0123@hotmail.com"
        git apply ../patches/brightness.patch
        git apply ../patches/rgb.patch
        git apply ../patches/rgb_flicker.patch
        
    
    - name: Push changes
      run: |
        git remote add repo https://github.com/Error-Project/frameworks_base 
        git checkout -b snow-patched
        git push -f
        github_token: ${{ secrets.GHTOKEN }}
